{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from tkinter.filedialog import askdirectory\n",
    " \n",
    "import pygame\n",
    "from mutagen.id3 import ID3\n",
    "from tkinter import *\n",
    "'''--------------basic window------------------'''\n",
    "root = Tk() \n",
    "\n",
    "\n",
    "frame=Frame(root, width=800, height=400, background=\"red\")\n",
    "frame.pack()\n",
    "\n",
    "\n",
    "root.minsize(800,400)\n",
    " \n",
    "listofsongs = []                               #storing music folder i list called listofsongs\n",
    "realnames = []\n",
    " \n",
    "v = StringVar()\n",
    "songlabel = Label(root,textvariable=v,width=100)\n",
    " \n",
    "index = 0  #selecting particular song from listofsongs\n",
    "\n",
    "'''-----------------select directory from which you want to import ur song folder------------------'''\n",
    " \n",
    "def directorychooser():\n",
    " \n",
    "    directory = askdirectory()                  #dialog box which will ask which folder to chose\n",
    "    os.chdir(directory)                         #changing current directory to directory chosen\n",
    "    \n",
    "  \n",
    "    for files in os.listdir(directory):         #pass the directory\n",
    "        if files.endswith(\".mp3\"):              #to check if its mp3 extenstion file or not\n",
    " \n",
    "            realdir = os.path.realpath(files)\n",
    "            audio = ID3(realdir)\n",
    "            realnames.append(audio['TIT2'].text[0])\n",
    " \n",
    " \n",
    "            listofsongs.append(files)             #append mp3 extenstion file\n",
    " \n",
    " \n",
    "    pygame.mixer.init()\n",
    "    pygame.mixer.music.load(listofsongs[0])       #play the first song in the list\n",
    "    #pygame.mixer.music.play()\n",
    "\n",
    "    \n",
    "directorychooser()\n",
    " \n",
    "def updatelabel():\n",
    "    global index\n",
    "    global songname\n",
    "    v.set(realnames[index])\n",
    "    #return songname\n",
    " \n",
    " \n",
    "def nextsong(event):\n",
    "    global index\n",
    "    index += 1\n",
    "    pygame.mixer.music.load(listofsongs[index])\n",
    "    pygame.mixer.music.play()\n",
    "    updatelabel()\n",
    "def prevsong(event):\n",
    "    global index\n",
    "    index -= 1\n",
    "    pygame.mixer.music.load(listofsongs[index])\n",
    "    pygame.mixer.music.play()\n",
    "    updatelabel()\n",
    " \n",
    " \n",
    "def stopsong(event):\n",
    "    pygame.mixer.music.stop()\n",
    "    v.set(\"\")\n",
    "    #return songname\n",
    " \n",
    "'''------------list box which will display all the song list----------------------'''\n",
    "\n",
    " \n",
    "label = Label(root,text='Music Player')\n",
    "label.pack()\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "listbox = Listbox(root)\n",
    "listbox.pack()\n",
    " \n",
    "#listofsongs.reverse()\n",
    "realnames.reverse()\n",
    " \n",
    "\n",
    "\n",
    "for items in realnames:\n",
    "    listbox.insert(0,items) #insert each elements to the list from left(0 means left)\n",
    "\n",
    "realnames.reverse()\n",
    "#listofsongs.reverse()\n",
    " \n",
    "'''----------------making buttons in  root window for next,previous  and stop the song------------'''\n",
    "\n",
    "nextbutton = Button(root,text = 'Next Song')            #increment the index\n",
    "nextbutton.pack()\n",
    " \n",
    "previousbutton = Button(root,text = 'Previous Song')    #decrement the index\n",
    "previousbutton.pack()\n",
    " \n",
    "stopbutton = Button(root,text='Stop Music')             # stop the music   \n",
    "stopbutton.pack() \n",
    " \n",
    "nextbutton.bind(\"<Button-1>\",nextsong)\n",
    "previousbutton.bind(\"<Button-1>\",prevsong)\n",
    "stopbutton.bind(\"<Button-1>\",stopsong)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    " \n",
    "songlabel.pack()\n",
    " \n",
    " \n",
    " \n",
    " \n",
    " \n",
    " \n",
    " \n",
    " \n",
    " \n",
    " \n",
    " \n",
    " \n",
    " \n",
    "root.mainloop()                                         # calling basic window"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
